import type {
  ActDefinition,
  DifficultyConfig,
  EnemyKind,
  SpawnBeat,
  UpgradeDefinition,
  UpgradeId,
  WeaponDefinition,
} from "./types.ts";

const pursuitWeights = {
  file: 5,
  media: 2,
  library: 1,
} satisfies Partial<Record<EnemyKind, number>>;
const duplicateWeights = {
  file: 2,
  media: 2,
  duplicate: 4,
  buffering: 1,
} satisfies Partial<Record<EnemyKind, number>>;
const rogueWeights = {
  malicious: 3,
  corruptor: 2,
  buffering: 2,
  support: 1,
  media: 1,
} satisfies Partial<Record<EnemyKind, number>>;

function beats(
  weights: Partial<Record<EnemyKind, number>>,
  budgets: [number, number, number],
): SpawnBeat[] {
  return [
    { at: 0, budget: budgets[0], weights },
    { at: 28, budget: budgets[1], weights },
    { at: 58, budget: budgets[2], weights },
  ];
}

export const ACTS: ActDefinition[] = [
  {
    id: "stale-stacks",
    name: "Stale Stacks",
    subtitle: "The backlog has become ambulatory.",
    palette: {
      background: "#06131b",
      grid: "rgba(104, 211, 181, 0.11)",
      primary: "#68d3b5",
      secondary: "#f8d477",
      danger: "#ff647c",
    },
    encounters: [
      {
        id: "first-sweep",
        act: 0,
        index: 0,
        name: "First Sweep",
        briefing: "Reclaim 26 GB before the stacks close in.",
        objective: "purge",
        target: 26,
        duration: 92,
        spawnInterval: 0.34,
        openingThreats: 5,
        threatFloor: 5,
        threatCap: 12,
        replenishMin: 0.28,
        replenishMax: 0.45,
        eliteChance: 0.12,
        beats: beats({ ...pursuitWeights, malicious: 1 }, [13, 17, 20]),
      },
      {
        id: "catalog-lock",
        act: 0,
        index: 1,
        name: "Catalog Lock",
        briefing: "Recover 10 volatile cache blocks before their checksums expire.",
        objective: "relay",
        target: 10,
        duration: 105,
        spawnInterval: 0.3,
        openingThreats: 7,
        threatFloor: 8,
        threatCap: 16,
        replenishMin: 0.24,
        replenishMax: 0.4,
        eliteChance: 0.14,
        relayDuration: 7,
        beats: beats({ ...pursuitWeights, malicious: 1 }, [16, 19, 23]),
      },
      {
        id: "retention-window",
        act: 0,
        index: 2,
        name: "Retention Window",
        briefing: "Survive the emergency retention purge.",
        objective: "survive",
        target: 92,
        duration: 92,
        spawnInterval: 0.27,
        openingThreats: 9,
        threatFloor: 10,
        threatCap: 20,
        replenishMin: 0.22,
        replenishMax: 0.36,
        eliteChance: 0.15,
        beats: beats({ ...pursuitWeights, malicious: 1, buffering: 1 }, [18, 22, 27]),
      },
    ],
    boss: {
      id: "backlog-behemoth",
      act: 0,
      name: "Backlog Behemoth",
      kind: "backlog",
      briefing: "A decade of “watch later” has achieved sentience.",
      health: 188,
      speed: 46,
      points: 1200,
    },
  },
  {
    id: "duplicate-vault",
    name: "Duplicate Vault",
    subtitle: "Every copy insists it is the original.",
    palette: {
      background: "#100b1d",
      grid: "rgba(182, 135, 255, 0.12)",
      primary: "#b687ff",
      secondary: "#65d6e8",
      danger: "#ff6f91",
    },
    encounters: [
      {
        id: "version-control",
        act: 1,
        index: 0,
        name: "Version Control",
        briefing: "Remove 36 redundant versions.",
        objective: "purge",
        target: 36,
        duration: 98,
        spawnInterval: 0.28,
        openingThreats: 8,
        threatFloor: 10,
        threatCap: 20,
        replenishMin: 0.22,
        replenishMax: 0.36,
        eliteChance: 0.16,
        beats: beats(duplicateWeights, [20, 25, 30]),
      },
      {
        id: "hash-check",
        act: 1,
        index: 1,
        name: "Hash Check",
        briefing: "Recover 12 mirrored cache blocks before they fork.",
        objective: "relay",
        target: 12,
        duration: 112,
        spawnInterval: 0.25,
        openingThreats: 10,
        threatFloor: 12,
        threatCap: 24,
        replenishMin: 0.2,
        replenishMax: 0.33,
        eliteChance: 0.18,
        relayDuration: 6,
        beats: beats({ ...duplicateWeights, corruptor: 1 }, [22, 28, 34]),
      },
      {
        id: "mirror-storm",
        act: 1,
        index: 2,
        name: "Mirror Storm",
        briefing: "Keep one authoritative version: you.",
        objective: "survive",
        target: 98,
        duration: 98,
        spawnInterval: 0.23,
        openingThreats: 11,
        threatFloor: 14,
        threatCap: 27,
        replenishMin: 0.18,
        replenishMax: 0.3,
        eliteChance: 0.19,
        beats: beats({ ...duplicateWeights, malicious: 1 }, [25, 32, 38]),
      },
    ],
    boss: {
      id: "duplicate-hydra",
      act: 1,
      name: "Duplicate Hydra",
      kind: "hydra",
      briefing: "Delete one head and two remuxes take its place.",
      health: 258,
      speed: 42,
      points: 2200,
    },
  },
  {
    id: "rogue-access",
    name: "Rogue Access",
    subtitle: "Someone shared the library with the entire internet.",
    palette: {
      background: "#160a13",
      grid: "rgba(255, 102, 132, 0.11)",
      primary: "#ff6684",
      secondary: "#76e0c1",
      danger: "#ffca69",
    },
    encounters: [
      {
        id: "session-revoke",
        act: 2,
        index: 0,
        name: "Session Revoke",
        briefing: "Terminate 42 hostile sessions.",
        objective: "purge",
        target: 42,
        duration: 104,
        spawnInterval: 0.24,
        openingThreats: 10,
        threatFloor: 14,
        threatCap: 27,
        replenishMin: 0.19,
        replenishMax: 0.31,
        eliteChance: 0.2,
        beats: beats(rogueWeights, [34, 42, 52]),
      },
      {
        id: "firewall-rebuild",
        act: 2,
        index: 1,
        name: "Firewall Rebuild",
        briefing: "Recover 14 access tokens before the sessions rotate.",
        objective: "relay",
        target: 14,
        duration: 118,
        spawnInterval: 0.21,
        openingThreats: 12,
        threatFloor: 16,
        threatCap: 30,
        replenishMin: 0.17,
        replenishMax: 0.28,
        eliteChance: 0.22,
        relayDuration: 5.5,
        beats: beats({ ...rogueWeights, duplicate: 1 }, [30, 38, 46]),
      },
      {
        id: "zero-trust",
        act: 2,
        index: 2,
        name: "Zero Trust",
        briefing: "Survive until every token has been rotated.",
        objective: "survive",
        target: 105,
        duration: 105,
        spawnInterval: 0.19,
        openingThreats: 14,
        threatFloor: 18,
        threatCap: 34,
        replenishMin: 0.15,
        replenishMax: 0.25,
        eliteChance: 0.24,
        beats: beats({ ...rogueWeights, duplicate: 1 }, [34, 43, 52]),
      },
    ],
    boss: {
      id: "rogue-admin",
      act: 2,
      name: "Rogue Admin",
      kind: "admin",
      briefing: "Privileges: excessive. Taste in media: indefensible.",
      health: 400,
      speed: 54,
      points: 4000,
    },
  },
];

export const DIFFICULTIES: Record<"normal" | "hard", DifficultyConfig> = {
  normal: {
    id: "normal",
    label: "Normal",
    spawnBudgetMultiplier: 1,
    enemySpeedMultiplier: 1,
    enemyHealthMultiplier: 1,
    projectileSpeedMultiplier: 1,
    warningMultiplier: 1,
    recoveryHealth: 1,
  },
  hard: {
    id: "hard",
    label: "Hard",
    spawnBudgetMultiplier: 1.3,
    enemySpeedMultiplier: 1.12,
    enemyHealthMultiplier: 1.18,
    projectileSpeedMultiplier: 1.16,
    warningMultiplier: 0.78,
    recoveryHealth: 0,
  },
};

export const WEAPONS: WeaponDefinition[] = [
  {
    id: "blaster",
    name: "Purge Blaster",
    description: "Fast, dependable deletion packets. Excellent at clearing small files.",
  },
  {
    id: "rail",
    name: "Deduper Rail",
    description: "Slow checksum rounds pierce targets and hit with double integrity damage.",
  },
  {
    id: "array",
    name: "Quarantine Array",
    description: "A three-way containment burst for controlling crowded sectors.",
  },
];

export const UPGRADES: UpgradeDefinition[] = [
  {
    id: "rapid-index",
    name: "Rapid Index",
    description: "+14% fire rate.",
    family: "firepower",
    maxLevel: 4,
  },
  {
    id: "packet-size",
    name: "Larger Packets",
    description: "+1 projectile damage.",
    family: "firepower",
    maxLevel: 3,
  },
  {
    id: "dedupe-pass",
    name: "Dedupe Pass",
    description: "Projectiles pierce one additional target.",
    family: "projectile",
    maxLevel: 3,
  },
  {
    id: "parallel-writes",
    name: "Parallel Writes",
    description: "Add a narrow companion shot.",
    family: "firepower",
    maxLevel: 2,
  },
  {
    id: "magazine-extension",
    name: "Magazine Extension",
    description: "+25% magazine capacity.",
    family: "firepower",
    maxLevel: 3,
  },
  {
    id: "hot-swap",
    name: "Hot Swap",
    description: "-16% reload time.",
    family: "firepower",
    maxLevel: 3,
  },
  {
    id: "index-accelerator",
    name: "Index Accelerator",
    description: "-12% Deep Scan cooldown.",
    family: "firepower",
    maxLevel: 3,
  },
  {
    id: "wide-query",
    name: "Wide Query",
    description: "+30% Deep Scan width.",
    family: "projectile",
    maxLevel: 2,
  },
  {
    id: "forked-scan",
    name: "Forked Scan",
    description: "Deep Scan adds two angled beams.",
    family: "projectile",
    maxLevel: 1,
  },
  {
    id: "fast-scan",
    name: "Fast Scan",
    description: "+10% movement speed.",
    family: "mobility",
    maxLevel: 4,
  },
  {
    id: "io-burst",
    name: "I/O Burst",
    description: "-18% dash cooldown.",
    family: "mobility",
    maxLevel: 3,
  },
  {
    id: "checksum",
    name: "Verified Checksum",
    description: "+20% dash duration.",
    family: "mobility",
    maxLevel: 2,
  },
  {
    id: "parity",
    name: "Parity Block",
    description: "+1 maximum integrity and heal 1.",
    family: "integrity",
    maxLevel: 2,
  },
  {
    id: "snapshot",
    name: "Clean Snapshot",
    description: "Gain a one-hit shield at each encounter.",
    family: "integrity",
    maxLevel: 1,
  },
  {
    id: "self-heal",
    name: "Self-Healing Array",
    description: "Recover 1 integrity after every encounter.",
    family: "integrity",
    maxLevel: 2,
  },
  {
    id: "combo-cache",
    name: "Combo Cache",
    description: "+35% combo window.",
    family: "combo",
    maxLevel: 3,
  },
  {
    id: "compression",
    name: "Lossless Compression",
    description: "+15% score from every deletion.",
    family: "combo",
    maxLevel: 3,
  },
  {
    id: "garbage-collector",
    name: "Garbage Collector",
    description: "Every tenth deletion repairs 1 integrity.",
    family: "integrity",
    maxLevel: 1,
  },
];

export const UPGRADE_BY_ID = Object.fromEntries(
  UPGRADES.map((upgrade) => [upgrade.id, upgrade]),
) as Record<UpgradeId, UpgradeDefinition>;
