/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibrariesKeyStaleRouteImport } from './routes/libraries.$key.stale'
import { Route as LibrariesKeyShowsRatingKeyRouteImport } from './routes/libraries.$key.shows.$ratingKey'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesKeyStaleRoute = LibrariesKeyStaleRouteImport.update({
  id: '/libraries/$key/stale',
  path: '/libraries/$key/stale',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesKeyShowsRatingKeyRoute =
  LibrariesKeyShowsRatingKeyRouteImport.update({
    id: '/libraries/$key/shows/$ratingKey',
    path: '/libraries/$key/shows/$ratingKey',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/libraries/$key/stale': typeof LibrariesKeyStaleRoute
  '/libraries/$key/shows/$ratingKey': typeof LibrariesKeyShowsRatingKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/libraries/$key/stale': typeof LibrariesKeyStaleRoute
  '/libraries/$key/shows/$ratingKey': typeof LibrariesKeyShowsRatingKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/libraries/$key/stale': typeof LibrariesKeyStaleRoute
  '/libraries/$key/shows/$ratingKey': typeof LibrariesKeyShowsRatingKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/setup'
    | '/libraries/$key/stale'
    | '/libraries/$key/shows/$ratingKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/setup'
    | '/libraries/$key/stale'
    | '/libraries/$key/shows/$ratingKey'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/settings'
    | '/setup'
    | '/libraries/$key/stale'
    | '/libraries/$key/shows/$ratingKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  LibrariesKeyStaleRoute: typeof LibrariesKeyStaleRoute
  LibrariesKeyShowsRatingKeyRoute: typeof LibrariesKeyShowsRatingKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/$key/stale': {
      id: '/libraries/$key/stale'
      path: '/libraries/$key/stale'
      fullPath: '/libraries/$key/stale'
      preLoaderRoute: typeof LibrariesKeyStaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/$key/shows/$ratingKey': {
      id: '/libraries/$key/shows/$ratingKey'
      path: '/libraries/$key/shows/$ratingKey'
      fullPath: '/libraries/$key/shows/$ratingKey'
      preLoaderRoute: typeof LibrariesKeyShowsRatingKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  LibrariesKeyStaleRoute: LibrariesKeyStaleRoute,
  LibrariesKeyShowsRatingKeyRoute: LibrariesKeyShowsRatingKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
