/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as IndexRouteImport } from './routes/index.tsx'
import { Route as ActivityRouteImport } from './routes/activity.tsx'
import { Route as ArcadeRouteImport } from './routes/arcade.tsx'
import { Route as DashboardRouteImport } from './routes/dashboard.tsx'
import { Route as DuplicatesRouteImport } from './routes/duplicates.tsx'
import { Route as SettingsRouteImport } from './routes/settings.tsx'
import { Route as SetupRouteImport } from './routes/setup.tsx'
import { Route as UsersRouteImport } from './routes/users.tsx'
import { Route as DeletionOperationsIdRouteImport } from './routes/deletion-operations.$id.tsx'
import { Route as SettingsSonarrRadarrRouteImport } from './routes/settings.sonarr-radarr.tsx'
import { Route as LibrariesKeyStaleRouteImport } from './routes/libraries.$key.stale.tsx'
import { Route as LibrariesKeyMoviesRatingKeyRouteImport } from './routes/libraries.$key.movies.$ratingKey.tsx'
import { Route as LibrariesKeyShowsRatingKeyRouteImport } from './routes/libraries.$key.shows.$ratingKey.tsx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeRoute = ArcadeRouteImport.update({
  id: '/arcade',
  path: '/arcade',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicatesRoute = DuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DeletionOperationsIdRoute = DeletionOperationsIdRouteImport.update({
  id: '/deletion-operations/$id',
  path: '/deletion-operations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSonarrRadarrRoute = SettingsSonarrRadarrRouteImport.update({
  id: '/sonarr-radarr',
  path: '/sonarr-radarr',
  getParentRoute: () => SettingsRoute,
} as any)
const LibrariesKeyStaleRoute = LibrariesKeyStaleRouteImport.update({
  id: '/libraries/$key/stale',
  path: '/libraries/$key/stale',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesKeyMoviesRatingKeyRoute =
  LibrariesKeyMoviesRatingKeyRouteImport.update({
    id: '/libraries/$key/movies/$ratingKey',
    path: '/libraries/$key/movies/$ratingKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const LibrariesKeyShowsRatingKeyRoute =
  LibrariesKeyShowsRatingKeyRouteImport.update({
    id: '/libraries/$key/shows/$ratingKey',
    path: '/libraries/$key/shows/$ratingKey',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/arcade': typeof ArcadeRoute
  '/dashboard': typeof DashboardRoute
  '/duplicates': typeof DuplicatesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/deletion-operations/$id': typeof DeletionOperationsIdRoute
  '/settings/sonarr-radarr': typeof SettingsSonarrRadarrRoute
  '/libraries/$key/stale': typeof LibrariesKeyStaleRoute
  '/libraries/$key/movies/$ratingKey': typeof LibrariesKeyMoviesRatingKeyRoute
  '/libraries/$key/shows/$ratingKey': typeof LibrariesKeyShowsRatingKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/arcade': typeof ArcadeRoute
  '/dashboard': typeof DashboardRoute
  '/duplicates': typeof DuplicatesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/deletion-operations/$id': typeof DeletionOperationsIdRoute
  '/settings/sonarr-radarr': typeof SettingsSonarrRadarrRoute
  '/libraries/$key/stale': typeof LibrariesKeyStaleRoute
  '/libraries/$key/movies/$ratingKey': typeof LibrariesKeyMoviesRatingKeyRoute
  '/libraries/$key/shows/$ratingKey': typeof LibrariesKeyShowsRatingKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/arcade': typeof ArcadeRoute
  '/dashboard': typeof DashboardRoute
  '/duplicates': typeof DuplicatesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/deletion-operations/$id': typeof DeletionOperationsIdRoute
  '/settings/sonarr-radarr': typeof SettingsSonarrRadarrRoute
  '/libraries/$key/stale': typeof LibrariesKeyStaleRoute
  '/libraries/$key/movies/$ratingKey': typeof LibrariesKeyMoviesRatingKeyRoute
  '/libraries/$key/shows/$ratingKey': typeof LibrariesKeyShowsRatingKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/arcade'
    | '/dashboard'
    | '/duplicates'
    | '/settings'
    | '/setup'
    | '/users'
    | '/deletion-operations/$id'
    | '/settings/sonarr-radarr'
    | '/libraries/$key/stale'
    | '/libraries/$key/movies/$ratingKey'
    | '/libraries/$key/shows/$ratingKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/arcade'
    | '/dashboard'
    | '/duplicates'
    | '/settings'
    | '/setup'
    | '/users'
    | '/deletion-operations/$id'
    | '/settings/sonarr-radarr'
    | '/libraries/$key/stale'
    | '/libraries/$key/movies/$ratingKey'
    | '/libraries/$key/shows/$ratingKey'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/arcade'
    | '/dashboard'
    | '/duplicates'
    | '/settings'
    | '/setup'
    | '/users'
    | '/deletion-operations/$id'
    | '/settings/sonarr-radarr'
    | '/libraries/$key/stale'
    | '/libraries/$key/movies/$ratingKey'
    | '/libraries/$key/shows/$ratingKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  ArcadeRoute: typeof ArcadeRoute
  DashboardRoute: typeof DashboardRoute
  DuplicatesRoute: typeof DuplicatesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SetupRoute: typeof SetupRoute
  UsersRoute: typeof UsersRoute
  DeletionOperationsIdRoute: typeof DeletionOperationsIdRoute
  LibrariesKeyStaleRoute: typeof LibrariesKeyStaleRoute
  LibrariesKeyMoviesRatingKeyRoute: typeof LibrariesKeyMoviesRatingKeyRoute
  LibrariesKeyShowsRatingKeyRoute: typeof LibrariesKeyShowsRatingKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade': {
      id: '/arcade'
      path: '/arcade'
      fullPath: '/arcade'
      preLoaderRoute: typeof ArcadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplicates': {
      id: '/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof DuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deletion-operations/$id': {
      id: '/deletion-operations/$id'
      path: '/deletion-operations/$id'
      fullPath: '/deletion-operations/$id'
      preLoaderRoute: typeof DeletionOperationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sonarr-radarr': {
      id: '/settings/sonarr-radarr'
      path: '/sonarr-radarr'
      fullPath: '/settings/sonarr-radarr'
      preLoaderRoute: typeof SettingsSonarrRadarrRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/libraries/$key/stale': {
      id: '/libraries/$key/stale'
      path: '/libraries/$key/stale'
      fullPath: '/libraries/$key/stale'
      preLoaderRoute: typeof LibrariesKeyStaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/$key/movies/$ratingKey': {
      id: '/libraries/$key/movies/$ratingKey'
      path: '/libraries/$key/movies/$ratingKey'
      fullPath: '/libraries/$key/movies/$ratingKey'
      preLoaderRoute: typeof LibrariesKeyMoviesRatingKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/$key/shows/$ratingKey': {
      id: '/libraries/$key/shows/$ratingKey'
      path: '/libraries/$key/shows/$ratingKey'
      fullPath: '/libraries/$key/shows/$ratingKey'
      preLoaderRoute: typeof LibrariesKeyShowsRatingKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsSonarrRadarrRoute: typeof SettingsSonarrRadarrRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSonarrRadarrRoute: SettingsSonarrRadarrRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  ArcadeRoute: ArcadeRoute,
  DashboardRoute: DashboardRoute,
  DuplicatesRoute: DuplicatesRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SetupRoute: SetupRoute,
  UsersRoute: UsersRoute,
  DeletionOperationsIdRoute: DeletionOperationsIdRoute,
  LibrariesKeyStaleRoute: LibrariesKeyStaleRoute,
  LibrariesKeyMoviesRatingKeyRoute: LibrariesKeyMoviesRatingKeyRoute,
  LibrariesKeyShowsRatingKeyRoute: LibrariesKeyShowsRatingKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
